#!/bin/sh
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ ! -x "$ESLINT" ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m (npm i --save --save-exact --dev eslint)"
  exit 1
fi

for FILE in $STAGED_FILES
do
  if [[ "$FILE"  =~ "api" ]] || [[ "$FILE"  =~ "test" ]] || [[ "$FILE"  =~ "app" ]]; then
    "$ESLINT" "$FILE"
    if [[ "$?" != 0 ]]; then
      echo "Please run npm run lint wrong styling."
      exit 1
    fi
  fi
done
echo "Commit Succeeded linting is okey"
exit 0
